### ISSUE TITLE
Prowler recoil

### ISSUE THREAD

**Issue by bigistayle** [Ushris/ApexAHK#2]
the prowler has really strange recoil it jumpes left and right up and down so its not really anti recoil but thx for the lstar update <3

**Comment by Ushris** [comment]
Yea, i dont have a way to do Prowler auto pattern right now, it works while burst.

**Comment by bigistayle** [comment]
no problem thank you that you update it youre the best :D

**Comment by Ushris** [comment]
Im working on a fix now, just havent had anything work well enough to deploy, and your welcome!

**Comment by bigistayle** [comment]
from the prowler on burst mode is fucked up too its drag to much down

**Comment by Ushris** [comment]
> from the prowler on burst mode is fucked up too its drag to much down

Updated the Pattern for Burst mode, try that.

**Comment by bigistayle** [comment]
> > from the prowler on burst mode is fucked up too its drag to much down
> 
> Updated the Pattern for Burst mode, try that.

nothing changed if you dont fast trigger it on burst mode all is fine but if you trigger fast it goes straight down here's a video
https://streamable.com/2t4x1y

**Comment by Ushris** [comment]
I JUST checked it, again. Make sure your settings are proper according to your ingame settings, Ive updated Prowler to Autofire while in burst mode by default, so go ahead and grab the latest release. 

https://cdn.discordapp.com/attachments/778481974524379147/1170759082437783613/i6PuujW.mp4?ex=655a355c&is=6547c05c&hm=adc3e78a60c4d50a076389310634f388580002720d13f32aaf7deb67a0592627&

Video showing that, Yes, it does work while in burst mode.
