### ISSUE TITLE
nemesis doesnt work

### ISSUE THREAD

**Issue by paperpandastacks** [Ushris/ApexAHK#3]
nemesis doesnt work. its not part of the detection. i've found the lines of code from mgsweet's version and added it in. the recoil pattern seems fine. but the gun does not fire smoothly sometimes it would just hold down the fire button sometimes the gun would feel jammed and not fire or have very delayed fire.

**Comment by Ushris** [comment]
Yea, see. Nemesis is there, does fire properly while charged, this jam feels like that because of the different fire rates from it charging. But no, Nemesis DOES get detected.

**Comment by paperpandastacks** [comment]
check your resolution files. nemesis is not even listed in there. so it does not get detected

**Comment by Ushris** [comment]
ah I see the issue. 

Wrong version of these files got placed

**Comment by Ushris** [comment]
there, I have reuploaded my files, Not exactly sure what happened there, but it seems like when i uploaded everything, i put Resolution files into the wrong place.

**Comment by Ushris** [comment]
As Far as the gunjam, you can try now, but it is made to FullAuto from the script while ramping, once it is rammed, Apex has the gun full auto, so itll full auto from there. It can "Jam" if you try to file it while your still on internal firing cooldown, if the gun cant be shot, and you click, itll till pull down.

**Comment by paperpandastacks** [comment]
weapon fires fine now. except the recoil pattern is terrible. the first couple bursts are good and then it starts drawing a circle around your target.

**Comment by Ushris** [comment]
This might be because of it fully ramping, last bit of the mag wont be accurate since the Fully ramped pattern is WAY different than the unramped
I added a change to Nemeis.txt to match the ramped version on the last 2 bursts, its a LITTLE more consistent, but not a huge difference

https://youtu.be/VcebdCLQb6w Test While Unramped
https://youtu.be/0jILmFD_Y3E Test While Ramped
Both of these are recorded BEFORE i made the change at all

**Comment by paperpandastacks** [comment]
try shooting something further away. at that distance you wouldnt need a recoil script

**Comment by Ushris** [comment]
I dont see your issue until your at around 60m away from your target and NOT moving- Which is kinda outside of what id be using a Nemesis for, therefor, i will not be changing its pattern. Its to assist your Recoil, not remove recoil entirely. It would be quite easy for a spectator to see you were cheating if you had perfect/near perfect recoil without moving your mouse, or the character.
