### ISSUE TITLE
复仇女神似乎不起作用

### ISSUE THREAD

**Issue by CDXCCCC** [Ushris/ApexAHK#6]
如题

**Comment by Ushris** [comment]
It should, can you make a screencap of your issue, aswell as tell me your res?

**Comment by CDXCCCC** [comment]
All the other guns work fine but not the Nemesis, I'm guessing it might be a recognition issue? My resolution is 1920*1080.
![Scripts not used](https://github.com/Ushris/ApexAHK/assets/53206076/e87954d9-0a69-4dbd-8180-d79d2f836821)
![Use of scripts - hemlok](https://github.com/Ushris/ApexAHK/assets/53206076/936f2c95-883c-4b38-933e-95a64b6567b3)
![Use of scripts - Nemesis](https://github.com/Ushris/ApexAHK/assets/53206076/0412821e-c44d-4951-bd93-54d3d688b9ea)

**Comment by CDXCCCC** [comment]
In  single shot gun, the 30-30 doesn't seem to work either, but the G7 does, but it doesn't matter. I still want the script to help my Nemesis at mid to long range XD

**Comment by CDXCCCC** [comment]
My friends and I all have this problem, so it's probably not a problem with our settings

**Comment by Ushris** [comment]
30-30 has no pattern at all.

I'll look into the issue with Nemesis on 1080p

**Comment by Ushris** [comment]
Can i see your settings?
![image](https://github.com/Ushris/ApexAHK/assets/81685996/750ec2aa-1c62-43f1-ad63-b1658ff86c0b)

**Comment by CDXCCCC** [comment]
![屏幕截图 2023-11-23 150715](https://github.com/Ushris/ApexAHK/assets/53206076/2d2f7e3c-4ef2-41f3-b9ee-568815fff1f2)

**Comment by Ushris** [comment]
Hello! i can confirm nemesis does work on 1920x1080. However, Turn off Auto_Fire, as weapons like p2020, have global autofire, and will shoot full auto with that setting off, and i recommend turning ADS_Only on, it can look odd if your hipfiring, up to you however. Just note it will not improve hipfire accuracy.

If it still doesnt seem to work, turn on Debug, ensure your windows is set to 1080p, and maybe, it could be a thing in your in a different language, but i dont think that would be the case, as i tested in English and Japanese with no issue.

**Comment by CDXCCCC** [comment]
Hi, just now I solved the problem, I downloaded a version on unkonwncheat [https://www.unknowncheats.me/forum/apex-legends/609300-apex-legends-ahk.html] and in this version Nemesis is working fine, but the The version on UC has an extra folder called "compile", maybe that's not the problem.
By the way, the author's name on the UC forums is iBliss, and your avatars are the same, so I'm guessing that's you, and if it is, you can check the files of both versions, which may reveal the problem.

**Comment by Ushris** [comment]
More likely than not, its Unknown taking a long time to verify files.
